{{- if and .Values.api.enabled .Values.api.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden-kubernetes-secrets.fullname" . }}-auth
  labels:
    {{- include "vaultwarden-kubernetes-secrets.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.api.auth.token }}
  token: {{ .Values.api.auth.token | b64enc | quote }}
  {{- else }}
  # Generate random token if not provided
  token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
