{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden-kubernetes-secrets.name" . }}
    app.kubernetes.io/part-of: {{ include "vaultwarden-kubernetes-secrets.name" . }}
{{- end }}
