{{- if .Values.rbac.create }}
{{- if .Values.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vaultwarden-kubernetes-secrets.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden-kubernetes-secrets.name" . }}
    app.kubernetes.io/part-of: {{ include "vaultwarden-kubernetes-secrets.name" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vaultwarden-kubernetes-secrets.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden-kubernetes-secrets.name" . }}
    app.kubernetes.io/part-of: {{ include "vaultwarden-kubernetes-secrets.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vaultwarden-kubernetes-secrets.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vaultwarden-kubernetes-secrets.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vaultwarden-kubernetes-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vaultwarden-kubernetes-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vaultwarden-kubernetes-secrets.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vaultwarden-kubernetes-secrets.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
