{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vaultwarden-kubernetes-secrets.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "vaultwarden-kubernetes-secrets.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
