apiVersion: v2
name: vaultwarden-kubernetes-secrets
description: Synchronize Bitwarden/Vaultwarden items to Kubernetes Secrets
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/antoniolago/vaultwarden-kubernetes-secrets
sources:
  - https://github.com/antoniolago/vaultwarden-kubernetes-secrets
keywords:
  - vaultwarden
  - bitwarden
  - secrets
  - kubernetes
